# Generated by Django 5.0.6 on 2024-06-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoUploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhotoName', models.CharField(max_length=200)),
                ('Photo', models.ImageField(upload_to='static/images')),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
