# Generated by Django 5.0.6 on 2024-06-28 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Photouploader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photouploader',
            name='PhotoName',
        ),
    ]
