# Generated by Django 5.0.6 on 2024-06-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photouploader', '0002_remove_photouploader_photoname'),
    ]

    operations = [
        migrations.AddField(
            model_name='photouploader',
            name='Photo_Name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
